apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: dashaun-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "10"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "15s"
    spec:
      containers:
        - image: dashaun/dev.dashaun.service.gateway:v0.0.20
