apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: dashaun-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: dashaun/dev.dashaun.service.gateway:v0.0.6